### ISSUE TITLE
Customizable .cookiecutterrc location

### ISSUE THREAD

**Issue by nfarrar** [audreyr/cookiecutter#510] opened 2015-09-09 14:41 UTC
Any chance cookiecutter could allow us to read from a cookiecutterrc file stored in another location (i.e. the XDG default: `~/.config/cookiecutter/config`). I *really* like having my home uncluttered - and lately have been trying to move my configuration files out as much as possible.

This could be done several simple ways:

1. Make cookiecutter check (by default) the current location & for an XDG compatible configuration file.
2. Add a *config* flag (`cookiecutter <...> --config=~/.config/cookiecutter/config`)
3. Read an environment variable, if it exists:

```
import os
config_file = os.getenv('COOKIECUTTER_CONFIG', '~/.cookiecutterrc`)
```

**Comment by audreyr** [comment] 2015-10-09 06:25
Closing as duplicate of #104, but I think this is something we should do sooner than later, since it's a violation of the XDG spec. Marking #104 as high-priority. Thanks @nfarrar.

**Closed by audreyr** 2015-10-09 06:25 UTC
