### ISSUE TITLE
Why git repo required in cookiecutter parameter ?

### ISSUE THREAD

**Issue by sp1rs** [audreyr/cookiecutter#478] opened 2015-07-28 13:58 UTC
I have template page in a repo. Let say my repo is   https://github.com/username/repo_name  and have my template pkg in it .
So why cant i do something like this ....

$ cookiecutter https://github.com/username/repo_name/template_pkg

**Comment by pydanny** [comment] 2015-07-28 18:28
Cookiecutter was designed to work with pulling repos and then working with the directory that cloning creates locally. It's not currently able to work with individual directories within repos because that's a bit more work. It's an interesting feature and one worth considering.

**Comment by hackebrot** [comment] 2015-07-30 17:04
Hi @sp1rs, as @pydanny already mentioned the desired syntax is not supported up to now.

You can do it by hand though:

```bash
$ git clone https://github.com/username/repo_name.git
$ cookiecutter repo_name/template_pkg
```

Please let me know if this works for you. :bow:

**Comment by sp1rs** [comment] 2015-07-31 04:44
@hackebrot That works . But what if i dont want to clone the repo and just want that template_pkg .

**Comment by pydanny** [comment] 2015-07-31 06:27
@sp1rs Here are some options for you:

1. Write a simple shell script that clones the repo then calls Cookicutter on your `template_pkg `.
2. Write a Python script that clones the repo then calls Cookicutter on your `template_pkg `.
3. Write a Python script that clones the repo, then uses the internal Cookiecutter API to render the `template_pkg`. See https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/main.py#L55
4. Move each `template_pkg` into its own repo. That's how Cookiecutter is designed to function: off individual repos or directories.

As for this feature request, upon reflection it is out of scope for Cookiecutter. It is also something that can be accomplished via any of the four items above, and three of those involve automation.

**Closed by pydanny** 2015-07-31 06:27 UTC
Labels: enhancement
