### ISSUE TITLE
Do not remove existing directory if UndefinedError is thrown

### ISSUE THREAD

**Issue by lieutdan13** [audreyr/cookiecutter#975] opened 2017-08-03 13:55 UTC
* Cookiecutter version: cookiecutter==1.5.1
* Template project url: irrelevant
* Python version: Python 2.7.6
* Operating System: Ubuntu 14.04

### Description:

When I run cookiecutter with the `-f` option against an existing output directory and I happen to have an undefined variable in my template, cookiecutter removes my directory via https://github.com/audreyr/cookiecutter/blob/2661e61491b68ecfabd568faed8b1dad0c6695ec/cookiecutter/generate.py#L329

I would expect the cookiecutter to honor an existing output directory before deciding to remove it upon throwing the Exception.

### What I've run:

```
mkdir cookiecutter_template
cd cookiecutter_template
virtualenv ~/.virtualenvs/cookiecutter_template
source ~/.virtualenvs/cookiecutter_template/bin/activate
pip install cookiecutter
echo '{ "project_slug": "my-slug" }' > cookiecutter.json
mkdir \{\{cookiecutter.project_slug\}\}
touch \{\{cookiecutter.project_slug\}\}/file
cookiecutter -o ../ ./ --no-input
ls -la ../my-slug/
echo "{{cookiecutter.invalid_variable}}" > \{\{cookiecutter.project_slug\}\}/file
cookiecutter -o ../ ./ --no-input -f
ls -la ../my-slug/
# ls: cannot access ../my-slug/: No such file or directory
```

**Comment by michaeljoseph** [comment] 2017-08-04 14:56
Hi @lieutdan13,

I'm closing this as a duplicate of #629, please have a look at the associated PR: #964.

Thanks for the issue :)

**Closed by michaeljoseph** 2017-08-04 14:56 UTC

**Comment by lieutdan13** [comment] 2017-08-04 16:16
I did my due diligence and looked through all open issues for this, but I must have missed #629

**Comment by michaeljoseph** [comment] 2017-08-04 16:49
No worries, thank you cutting code to fix this anyways... ❤️
