### ISSUE TITLE
CLI way to specify parameters

### ISSUE THREAD

**Issue by satreix** [audreyr/cookiecutter#646] opened 2016-03-10 19:55 UTC
I would like to have a way to specify one/several parameters in `cookiecutter` from the command line. The point being I know the template I am using, and I am willing to use the defaults values except from some of them.

Something like:

```
cookiecutter gh://... --extra-vars key=value --no-input
cookiecutter gh://... --extra-vars '{"key": "value"}' --no-input
```

How would you feel about that?

**Comment by michaeljoseph** [comment] 2016-03-11 12:03
@satreix This is a dupe of #389 and we have an in-flight PR: #400

**Closed by michaeljoseph** 2016-03-11 12:03 UTC
