### ISSUE TITLE
Cookiecutter Generation Issue for 1.1.0+

### ISSUE THREAD

**Issue by kevinastone** [audreyr/cookiecutter#561] opened 2015-10-21 17:12 UTC
Our cookiecutter template works fine in `1.0.0`, but fails for `1.1.0` and `1.2.1` with:
```
DEBUG config.py: config_path is $HOME/.cookiecutterrc
DEBUG utils.py: Making sure path exists: $HOME/.cookiecutter_replay/
DEBUG find.py: Searching $HOME/.cookiecutters/$MY_COOKIECUTTER for the project template.
DEBUG find.py: The project template appears to be $HOME/.cookiecutters/$MY_COOKIECUTTER/{{cookiecutter.repo_name}}
DEBUG generate.py: Generating project from $HOME/.cookiecutters/$MY_COOKIECUTTER/{{cookiecutter.repo_name}}...
DEBUG generate.py: Rendered dir  must exist in output_dir .
Error: "." directory already exists
```

**Comment by hackebrot** [comment] 2015-10-21 18:04
Hi @kevinastone! :wave: 

Any chance you can provide us with a full traceback?

**Comment by kevinastone** [comment] 2015-10-21 18:41
```
kevinstone@kwmbp ~/e/test> cookiecutter -v git@github.com:$MY_ORG/$MY_REPO.git
DEBUG config.py: config_path is $HOME/.cookiecutterrc
DEBUG utils.py: Making sure path exists: $HOME/.cookiecutters/
DEBUG vcs.py: repo_dir is $HOME/.cookiecutters/$MY_REPO
You've cloned $HOME/.cookiecutters/$MY_REPO before. Is it okay to delete and re-clone it? [yes]: 
Cloning into '$MY_REPO'...
remote: Counting objects: 443, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 443 (delta 68), reused 58 (delta 58), pack-reused 370
Receiving objects: 100% (443/443), 53.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (244/244), done.
Checking connectivity... done.
DEBUG main.py: context_file is $HOME/.cookiecutters/$MY_REPO/cookiecutter.json
DEBUG generate.py: Context generated is {u'cookiecutter': OrderedDict([(u'service_name', u'cookie'), (u'intial_version', u'0.1.0'), (u'service_description', u'A service to do stuff'), (u'django_secret_key', u'$TOKEN'), (u'parse_auth_token', True), (u'verify_auth_token', False), (u'haproxy_listen_port', 9900), (u'nginx_listen_port', 9901), (u'uwsgi_listen_port', 9902)])}
service_name [cookie]: 
intial_version [0.1.0]: 
service_description [A service to do stuff]: 
django_secret_key [$TOKEN]: 
parse_auth_token [True]: 
verify_auth_token [False]: 
haproxy_listen_port [9900]: 
nginx_listen_port [9901]: 
uwsgi_listen_port [9902]: 
DEBUG config.py: config_path is $HOME/.cookiecutterrc
DEBUG utils.py: Making sure path exists: $HOME/.cookiecutter_replay/
DEBUG find.py: Searching $HOME/.cookiecutters/$MY_REPO for the project template.
DEBUG find.py: The project template appears to be $HOME/.cookiecutters/$MY_REPO/{{cookiecutter.repo_name}}
DEBUG generate.py: Generating project from $HOME/.cookiecutters/$MY_REPO/{{cookiecutter.repo_name}}...
DEBUG generate.py: Rendered dir  must exist in output_dir .
Error: "." directory already exists
```

**Comment by pydanny** [comment] 2015-10-21 18:46
Just confirmed this bug is occurring on Mac OSX using Python 2.7.

**Comment by michaeljoseph** [comment] 2015-10-23 16:39
@kevinastone This is because your `cookiecutter.json` is missing a `repo_name` key I think.

**Comment by pydanny** [comment] 2015-10-23 16:46
@michaeljoseph, @kevinastone I just confirmed that the repo in question's `cookiecutter.json` is missing a `repo_name` field. Am submitting a patch for it now and closing this issue.

**Closed by pydanny** 2015-10-23 16:46 UTC
Labels: bug

**Comment by michaeljoseph** [comment] 2015-10-23 16:52
Looks like this change was introduced in #471.

**Comment by pydanny** [comment] 2015-10-23 16:54
The repo in question uses a different field name for the base directory than `repo_name`, hence why it breaks when other similar packages do not. :+1:
